language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules

before_install: 
- cd client

jobs:
  include:
    - stage: Lint, Test, Build
    - name: Lint
      script:
        - cd ..
        - npm install
        - npm run lint
    - name: Test
      script:
        - npm install
        - npm test -- --coverage
        - cd ..
        - npm install
        - npm run test
    - name: Build
      script: 
        - cd ..
        - npm install
        - npm run build
